diff --git a/Makefile.include b/Makefile.include
index 36b5e06..191b167 100644
--- a/Makefile.include
+++ b/Makefile.include
@@ -61,7 +61,7 @@ UPPERCASE = _ABCDEFGHIJKLMNOPQRSTUVWXYZ
 TARGET_UPPERCASE := ${strip ${shell echo $(TARGET) | sed y!$(LOWERCASE)!$(UPPERCASE)!}}
 CFLAGS += -DCONTIKI=1 -DCONTIKI_TARGET_$(TARGET_UPPERCASE)=1
 
-MODULES += core/sys core/dev core/lib
+MODULES += core/letmecreate/click core/letmecreate/bosch core/letmecreate/core core/sys core/dev core/lib
 
 # Include IPv6, IPv4, and/or Rime
 

